[package]
name = "graxus-server"
version.workspace = true
edition = "2021"

[dependencies]
graxus-core = { path = "../graxus-core" }
graxus-docgraph = { path = "../graxus-docgraph" }
graxus-codemap = { path = "../graxus-codemap" }
graxus-index = { path = "../graxus-index" }
graxus-agent-api = { path = "../graxus-agent-api" }
serde.workspace = true
serde_json.workspace = true
serde_repr = "0.1"
anyhow.workspace = true
tracing.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "io-util"] }
subtle.workspace = true

[dev-dependencies]
tempfile = "3"
